### ISSUE TITLE
动作识别中的daytime_pretrained

### ISSUE THREAD

**Issue by leb-2** [Red-Fairy/ZeroShotDayNightDA#3]
动作识别中的daytime_pretrained模型是在什么数据上预训练的

**Comment by Red-Fairy** [comment]
Hi,

I appreciate your interest in our project!

To maintain clarity and accessibility, I prefer to conduct discussions in English on github, which also helps prevent the repetition of questions.

The daytime model has been pre-trained using the Kinetics dataset, following the approach in ARID. You can review the implementation in their code [here](https://github.com/xuyu0010/ARID_v1/blob/master/network/resnet_i3d.py#L102). The model was then fine-tuned using the daytime dataset from the CVPR'22 UG2 challenge.

Best regards,
Rundong
